name = "Latający Statek"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f161be80613fce4d63648bc4c6231b6bf572951d9572676f88f9c904375dd36e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
