name = "Latający Statek"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a859bb2cf70c4e6cff4f82e37b812aa2ed951b07d4af580b12211f4d3ada75"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
