name = "Latający Statek"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d341bc9ddd97d6981e98be0b557346755beaccba0a5c78e1091f03965eeafdaf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
