name = "NeoFFTV"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a16dbb524bb5442713f65d17563f1228f726d8afcaf8a1d06e1342db1d0f1c16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
