name = "NeoFFTV"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a752ad44c817da9ba06319d82ab3c232f8142f49b441245116888c0207e59a8f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
