name = "NeoFFTV"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c60412b6e79a66f0c688a736d992fc5251650075ab5d533cf38353a86403c7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
