name = "FFTV Achoo!"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef1b6e044345bf7e6f379d3be3f88180d109bf97325a3dff3443e31647c7c840"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.59-beta"
