name = "XP to Ewolucja dinozaura"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6c0822e0cd67521784933bc2ee514e4cad9fac68f015590140a4c44453e7896"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
