name = "XP to Ewolucja dinozaura"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca39be06ba872379e6b4047e6fe18d6a4bf486b31d81a1b9811a3d282af8d128"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
