name = "XP to Ewolucja dinozaura"
author = "karolkuter-boop"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b25ee8694c5e9c0b24d98a4995d3fbb82009b3cc82048c6e2a52aee68687623"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
