name = "CML NeoFFTV"
author = "karolkuter-boop"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d9e06b34abb5ae94b0a1a17f3412ab384d761e1ba654c2bcd4acc84fbc24b8a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
