name = "CML NeoFFTV"
author = "karolkuter-boop"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6588ccb4057c5f93d06114c0b9e9bde9f1a8833de23305c3197d4cb22f0e56a2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
